### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by joweihsieh** [Aez35/miRScore#20]
Hi,

Thanks for developing this.
I downloaded the current commit and run "miRScore -h", and I encountered an error:

  File "/home/jhsieh/miniconda3/envs/miRScore/bin/miRScore", line 107
    f"cat ../{input_file} | sed -E '/(>)/!s/U/T/g' > {output_file}",
                                                                  ^
SyntaxError: invalid syntax

Could you please help me to fix this?
Thanks,
Jo-Wei

**Comment by Aez35** [comment]
Hi Jo-Wei,

This error suggests that perhaps your python isn't recognizing the f-string. Please check your version of python is updated (at least V3.6). If the error persists, please share your command and python version and I can assist further!

Best,
Allison

**Comment by joweihsieh** [comment]
Hi Allison,

Thanks for the response.
I discovered that my environment ($PATH) prioritizes a lower version of Python instead of a higher one.
After fixing this, the script works now.

Thanks,
Jo-Wei

**Comment by Aez35** [comment]
Great, glad you were able to resolve this! I will include a check in future commits.

Best,
Allison
