### ISSUE TITLE
autotrim message ambiguity

### ISSUE THREAD

**Issue by MikeAxtell** [Aez35/miRScore#22]
The message spawned by `autotrim` states:

```
Using ath-miR166a sequence for trimming: UCGGACCAGGCUUCAUUCCCC
```

This could be taken to mean that the sequence UCGGACCAGGCUUCAUUCCCC is the adapter being searched for. Suggest re-wording as follows:

```
-trimkey used for discovering adapter sequence: UCGGACCAGGCUUCAUUCCCC
```

**Comment by Aez35** [comment]
Message updated for clarity.
