### ISSUE TITLE
reads.csv pass/fail bugs and clarifications

### ISSUE THREAD

**Issue by MikeAxtell** [Aez35/miRScore#23]
As of 4b8b45b the reads.csv output file has some bugs and discrepancies with the documentation in the README.

- The README states that reads.csv "_Also includes a Pass/Fail result. A 'Pass' indicates the miRNA meets the read floor and has a precision greater than 75% in that library. A 'Fail' indcates one of these criteria are not met_." However, it also appears cases where 0 miRNA and/or miRNA-star reads are also called 'Fail' in reads.csv. Calling a 'Fail' if there are 0 reads for either/both the miRNA/miRNA* is the correct behavior. However, this should be documented in the README, which currently does not state that criterion.
- The addition of a 'flags' column to reads.csv would greatly enhance user understanding why certain cases fail.
- Here is an example snippet from a reads.csv file, showing analysis for a single locus 'Cluster_1308' in three FASTQ files:
![image](https://github.com/Aez35/miRScore/assets/6854537/3a8dbeba-39ee-46be-afeb-7534e30b9c18)
you can see that it has a 'Pass' in the third case. BUT, there are fewer than 10 total reads in that case.  According to the README, it should be a 'Fail' in that third line due to less than 10 total reads. In the overall 'miRScore_results.csv' output file, this locus is given a 'Fail'. Which seems correct because all three libraries failed. Just that the reads.csv is not correctly reporting the 'result'.

**Comment by Aez35** [comment]
Fixed as of [657feba](https://github.com/Aez35/miRScore/commit/657feba662434d58d556ab72de8a81b263a4c3eb).

**Comment by MikeAxtell** [comment]
The README still needs to be updated to accurately describe all of the possible conditions that can cause a 'Fail' in a reads.csv line. Right now the README does not mention lack of mature miRNA and/or star reads as a possible failure cause.

**Comment by MikeAxtell** [comment]
Also, what about the addition of a 'flags' column to reads.csv?

**Comment by Aez35** [comment]
Fixed as of commit [fefe4a6](https://github.com/Aez35/miRScore/commit/fefe4a61bec893e599b953789900ae3d101025dd)

Thank you
