### ISSUE TITLE
Usage message incorrect - fastq is required

### ISSUE THREAD

**Issue by MikeAxtell** [Aez35/miRScore#24]
As of fefe4a6 the usage message states:

```
usage: miRScore-fefe4a6 [-h] [-fastq [FASTQ ...]] -mature MATURE -hairpin HAIRPIN [-mm [MM]]
                        [-n N] [-nostrucvis [NOSTRUCVIS]] [-threads THREADS] -kingdom
                        {plant,animal} [-star STAR] [-out OUT] [-autotrim [AUTOTRIM]]
                        [-trimkey TRIMKEY]
miRScore-fefe4a6: error: the following arguments are required: -mature, -hairpin, -kingdom
```

Option `-fastq` is shown as optional, but in fact it is required. The brackets should be removed from the usage example, and the error message needs to include `-fastq` in the list of required arguments.

**Comment by Aez35** [comment]
Artifact of bam removal. Updated in commit [26bb3c6](https://github.com/Aez35/miRScore/commit/26bb3c65ca9ca66752b3630578debb4b9d6d6454)
