### ISSUE TITLE
Speed up samtools steps

### ISSUE THREAD

**Issue by thalescherubino** [Aez35/miRScore#25]
Hi,

I am using miRScore on a set of 42 sRNA libraries and have noticed a bottleneck in some Samtools steps, such as sorting, merging, and converting SAM to BAM. I wonder if it would be beneficial to allow Samtools to utilize multiple threads by using the -@ option.

Best regards,
Thales

**Comment by Aez35** [comment]
Thank you as always for the suggestions. This was planned to be done with the next commit as there are quite a few changes coming, however I added it now.  It is available as of commit [3c6d0af](https://github.com/Aez35/miRScore/commit/3c6d0af7e0947a0b37ad1c729e64b758e7b971bf)
