### ISSUE TITLE
proposed change the example command 

### ISSUE THREAD

**Issue by thalescherubino** [Aez35/miRScore#26]
Hi, 

I am trying to run the example but it did not work, I had to change to:

miRScore -mature ./TestData/ath_miRBase_miRNAs.fa -hairpin ./TestData/ath_miRBase_precursors.fa -fastq fastqs/* -kingdom plant -autotrim

**Comment by Aez35** [comment]
Thank you for the input. The instructions say to place the files in your working directory.
