### ISSUE TITLE
TypeError: can only concatenate str (not "int") to str

### ISSUE THREAD

**Issue by thalescherubino** [Aez35/miRScore#27]
Hi Alli,

adding the multi-thread support might have caused this error in the new release.

> Library trimming:   0%|                              | 0/5 [00:00<?, ?it/s]Trimming ../SRAfastqs/SRR12224689.fastq...
> Adapter detected: TGGAATTCTCGGGTGC
> Library trimming:   0%|                              | 0/5 [00:16<?, ?it/s]
> Traceback (most recent call last):
>   File "/newdata/data1/homes/tcherubino/MIRSCORE/HOPS/./miRScore-main/miRScore", line 1122, in <module>
>     main()
>   File "/newdata/data1/homes/tcherubino/MIRSCORE/HOPS/./miRScore-main/miRScore", line 643, in main
>     cmd='cutadapt -j '+ args.threads + ' -a '+ output + ' -o '+ tfile + ' --discard-untrimmed -m 12 --report minimal ' +fastq
> TypeError: can only concatenate str (not "int") to str

**Comment by Aez35** [comment]
Intriguingly, I don't get this error. I have amended the script to reflect strings instead of integers for all thread arguments. Please try again with commit [4f27838](https://github.com/Aez35/miRScore/commit/4f27838d4985135093df81ee09c56946774c98b7).
