### ISSUE TITLE
Example / testing

### ISSUE THREAD

**Issue by MikeAxtell** [Aez35/miRScore#32]
The example/testing portion of the README mentions Arabidopsis data, but the contents of the "TestData" folder contain rice hairpins and rice matures. The example directs the user to download sRNA-seq data from Arabidopsis. The README example and the actual contents of TestData need to be synchronized. As it stands, users cannot follow the Example data to test the script because the actual contents of TestData are for a different species.

**Comment by MikeAxtell** [comment]
Related to this: When you revise the TestData, you should include "clean" hairpin and mature files. By "clean" I mean that they should just run with no errors. You current "osa" example files will not run because of mismatches between names of hairpins and matures. Users should not have to resort to using "hairpinHelper" just to run the example. The example data should use our ideal format where there is a one-to-one exact name correspondence between hairpin entry and mature miRNA entry.

**Comment by MikeAxtell** [comment]
More related to this: 
The test data should be small (like 10-20 loci), all should be clean and runnable without having to use hairpinHelper and without issues of mature starting at position 1. And all names should be in our preferred format ("ath-miR166a" --> "ath-MIR166a" ... e.g. exact matches in name except for upper/lower case of "mir"). This will allow users to run a very fast example and to serve as a guide for users as to the ideal format of the data.

**Comment by Aez35** [comment]
This has been resolved, thank you.
